#
# application.yml — главный конфигурационный файл Spring Boot.

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    username: bank_user
    password: bank_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  liquibase:
    change-log: classpath:db.migration/changes/changelog-master.yaml

app:
  jwt-secret: mySecretKeyForJWTGeneration12345
  jwt-expiration-ms: 86400000
